# Generated by Django 4.1.7 on 2023-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/EmployeeProfilePic/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='regin',
            field=models.CharField(choices=[('Madurai North', 'Madurai North'), ('Madurai South', 'Madurai South'), ('Madurai East', 'Madurai East'), ('Madurai West', 'Madurai West'), ('Madurai Central', 'Madurai Central')], max_length=50, null=True),
        ),
    ]
