# Generated by Django 4.1.7 on 2023-03-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_customer_profile_pic_employee_profile_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='House_maintan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqft', models.PositiveIntegerField()),
                ('pub_date', models.DateField(auto_now_add=True, null=True)),
                ('specification', models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK'), ('5BHK', '5BHK')], max_length=50, null=True)),
                ('regin', models.CharField(choices=[('Madurai North', 'Madurai North'), ('Madurai South', 'Madurai South'), ('Madurai East', 'Madurai East'), ('Madurai West', 'Madurai West'), ('Madurai Central', 'Madurai Central')], max_length=50, null=True)),
                ('location', models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], max_length=50, null=True)),
                ('use', models.BooleanField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.customer')),
            ],
        ),
    ]
