# Generated by Django 4.1.7 on 2023-04-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_house_maintan_status_house_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_maintan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='houseimages/'),
        ),
    ]
