# Generated by Django 4.1.7 on 2023-04-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0005_house_maintan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_maintan',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='house_maintan',
            name='rent',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='house_maintan',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
