# Generated by Django 4.1.7 on 2023-04-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0008_alter_house_sales_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_maintan',
            name='use',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='house_sales',
            name='sqft',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
