# Generated by Django 4.1.7 on 2023-04-12 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0012_alter_house_maintan_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_maintan',
            name='status',
            field=models.CharField(choices=[('Submited', 'Submited'), ('Under Verification', 'Under Verification'), ('Processing', 'Processing'), ('On Rent', 'On Rent'), ('Under Maintanance', 'Under Maintanance'), ('Order Cancled', 'Order Cancled')], default='Submited', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='land_sales',
            name='status',
            field=models.CharField(choices=[('Submited', 'Submited'), ('Under Verification', 'Under Verification'), ('Processing', 'Processing'), ('Found Buyer', 'Found Buyer'), ('Sold', 'Sold'), ('Order Cancled', 'Order Cancled')], default='Submited', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='emp_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=70, null=True)),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.employee')),
                ('House_sales', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.house_sales')),
                ('house_maintan', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.house_maintan')),
                ('land_sales', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.land_sales')),
            ],
        ),
    ]
