# Generated by Django 4.1.7 on 2023-04-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0014_house_sales_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_sales',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
