# Generated by Django 4.1.7 on 2023-04-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0015_house_sales_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='land_sales',
            name='address',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='house_sales',
            name='status',
            field=models.CharField(choices=[('Submited', 'Submited'), ('Under Verification', 'Under Verification'), ('Processing', 'Processing'), ('Found Buyer', 'Found Buyer'), ('Sold', 'Sold'), ('Order Cancled', 'Order Cancled')], default='Submited', max_length=100, null=True),
        ),
    ]
