# Generated by Django 4.1.7 on 2023-04-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0016_land_sales_address_alter_house_sales_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_orders',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='emp_orders',
            old_name='House_sales',
            new_name='house_sales',
        ),
    ]
