# Generated by Django 4.1.7 on 2023-04-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0017_rename_employee_emp_orders_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land_sales',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
