# Generated by Django 4.1.7 on 2023-04-16 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0018_alter_land_sales_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emp_orders',
            name='house_maintan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.house_maintan'),
        ),
        migrations.AlterField(
            model_name='emp_orders',
            name='house_sales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.house_sales'),
        ),
        migrations.AlterField(
            model_name='emp_orders',
            name='land_sales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.land_sales'),
        ),
        migrations.CreateModel(
            name='customer_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.customer')),
                ('house_maintan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.house_maintan')),
                ('house_sales', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.house_sales')),
                ('land_sales', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.land_sales')),
            ],
        ),
    ]
