# Generated by Django 4.1.7 on 2023-04-17 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0020_alter_customer_orders_house_maintan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_orders',
            name='status',
            field=models.CharField(choices=[('Submited', 'Submited'), ('Processing', 'Processing'), ('Sold', 'Sold'), ('Order Cancled', 'Order Cancled')], default='Submited', max_length=70),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.customer')),
                ('house_maintan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.house_maintan')),
                ('house_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.house_sales')),
                ('land_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.land_sales')),
            ],
        ),
    ]
